# minio - To be applied to the kubernetes cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
    namespace: minio
  name: minio
  namespace: minio
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: minio
      namespace: minio
  template:
    metadata:
      labels:
        app: minio
        namespace: minio
    spec:
      containers:
      - args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-auth
              key: username
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-auth
              key: password
        image: minio/minio:edge
        imagePullPolicy: IfNotPresent
        name: minio
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
          subPath: minio
      volumes:
        - name: data
          hostPath:
            path: /var/local/feast/minio
            type: DirectoryOrCreate

---
# Minio Serveice
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
    namespace: minio
  name: minio
  namespace: minio
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 31386
  selector:
    app: minio
    namespace: minio